### ISSUE TITLE
syntax-php results are incorrect

### ISSUE THREAD

**Issue by llaville** [cytopia/awesome-ci#10]
Hello @cytopia 

I used `syntax-php` script inside my devilbox php container, and i've discover that results are not correct.
When I launch command `syntax-php --path=src/`

It will print 

$ find src/ -type f    -print0 | xargs -0 -P 4 -n1  sh -c 'if [ -f "${1}" ]; then php -d display_errors=1 -d error_reporting=-1 -l "$1" 2>&1 1>/dev/null || true; fi' --
[OK]  No files with PHP syntax errors found.

But one of my script was in syntax error, and i don't find it until execute.
Individual php lint command works as expected

php -l src/path/to/file/in/error/script.php

Parse error: syntax error, unexpected ':' in src/path/to/file/in/error/script.php on line 27

Real script file name was ofuscated, but context are identical !

**Comment by cytopia** [comment]
@llaville do you have a file structure with which I can reproduce it locally?

**Comment by llaville** [comment]
@cytopia Take any php script and replace EOL semicolon, by a colon dot.

```php
class Foo
{
    public $someProperty:

    public function someMethod()
    {
        $someVar = time():
    }
}
```

```bash
devilbox@php-7.2.29 in /shared/backups/bartlett/umlWriter $ php -l src/dummy.php

Parse error: syntax error, unexpected ':', expecting ',' or ';' in src/dummy.php on line 5
Errors parsing src/dummy.php
devilbox@php-7.2.29 in /shared/backups/bartlett/umlWriter $ syntax-php --path=src
$ find src -type f    -print0 | xargs -0 -P 12 -n1  sh -c 'if [ -f "${1}" ]; then php -d display_errors=1 -d error_reporting=-1 -l "$1" 2>&1 1>/dev/null || true; fi' --
[OK]  No files with PHP syntax errors found.
```
